### ISSUE TITLE
I have little confused about your implementation of the Outer Decoder

### ISSUE THREAD

**Issue by meiguoofa** [Dorian25/colorization-transformer-experimental#1]
In your outer decoder , you apply attention  on all rows at once  rather than like the paper's described one row once time？Is there something wrong with my understanding of your code?Looking forward to your reply！Thanks!!

**Comment by Dorian25** [comment]
First of all, thank you for your interest in our implementation ;) 

You're right, we apply attention on all rows at once because we need the index "i" to get the current row and for applying the mask of the _conditional masked column attention_. 
I think when they say in the paper "the outer is run once per-row" is just to get the index "i", but maybe we're wrong ?

For you what is the dimension of the output of the outer decoder ?

**Comment by meiguoofa** [comment]
Thank you for your reply ,actually I can't answer you about the dimension of the output of the outer decoder :) , The official TF version is too difficult to me,luckily I found this project implemented by you this is more suitable for my understanding, so thank you for your work . 

In this paper , the author  claimed the pixel i,j generated from all pixels before it , like position at (2,2) pixel generated from all pixels in the first row and the first pixel in second row ,but in your code , the row and column attention applied in th decoder , Do you think your code implements the way described in the paper? I' new to Transformer, so there are some questions really puzzle me.

**Comment by Dorian25** [comment]
I understand exactly what you mean ! ^^ The official code was difficult to understand !
So yeah, some parts of the code are **our own interpretation** of the paper (because there were blurred areas in the paper)...
Also, we did not manage to run the model on real images + with the dimensions mentioned in the paper ^^" (only with some tiny random noise image 4*4 and 8*8) but I clearly intend to continue the implementation of this paper in the near future !

**Comment by meiguoofa** [comment]
∩__∩ , looking forward to the result of your work！
